///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HistoryDataModelLinks {
/*
{
  "article": "http://www.spacex.com/news/2013/02/11/flight-4-launch-update-0",
  "wikipedia": "https://en.wikipedia.org/wiki/Falcon_1"
}
*/

  String? article;
  String? wikipedia;

  HistoryDataModelLinks({
    this.article,
    this.wikipedia,
  });
  HistoryDataModelLinks.fromJson(Map<String, dynamic> json) {
    article = json["article"]?.toString();
    wikipedia = json["wikipedia"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["article"] = article;
    data["wikipedia"] = wikipedia;
    return data;
  }
}

class HistoryDataModel {
/*
{
  "id": 1,
  "title": "Falcon 1 Makes History",
  "event_date_utc": "2008-09-28T23:15:00Z",
  "event_date_unix": 1222643700,
  "flight_number": 4,
  "details": "Falcon 1 becomes the first privately developed liquid fuel rocket to reach Earth orbit.",
  "links": {
    "article": "http://www.spacex.com/news/2013/02/11/flight-4-launch-update-0",
    "wikipedia": "https://en.wikipedia.org/wiki/Falcon_1"
  }
}
*/

  int? id;
  String? title;
  String? eventDateUtc;
  int? eventDateUnix;
  int? flightNumber;
  String? details;
  HistoryDataModelLinks? links;

  HistoryDataModel({
    this.id,
    this.title,
    this.eventDateUtc,
    this.eventDateUnix,
    this.flightNumber,
    this.details,
    this.links,
  });
  HistoryDataModel.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    title = json["title"]?.toString();
    eventDateUtc = json["event_date_utc"]?.toString();
    eventDateUnix = json["event_date_unix"]?.toInt();
    flightNumber = json["flight_number"]?.toInt();
    details = json["details"]?.toString();
    links = (json["links"] != null) ? HistoryDataModelLinks.fromJson(json["links"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["title"] = title;
    data["event_date_utc"] = eventDateUtc;
    data["event_date_unix"] = eventDateUnix;
    data["flight_number"] = flightNumber;
    data["details"] = details;
    if (links != null) {
      data["links"] = links!.toJson();
    }
    return data;
  }
}
